export const CHANGE_INPUT_VALUE = 'change-input-value'
export const ADD_ITEM = 'add-item'
export const DELETE_ITEM = 'delete-item'
export const INIT_LIST_ACTION = 'init-list-action'
export const GET_INIT_LIST = 'get_init_list'
